### ISSUE TITLE
Failed to run convert.py

### ISSUE THREAD

**Issue by QFaceblue** [Ma-Dan/keras-yolo4#14]
Failed to run convert.py. And there is no error message.

**Comment by zylxadz** [comment]
I have run sucessfully.Maybe you can try again.
python :3.6
tensorflow :1.14.0
keras:2.2.5

**Comment by QFaceblue** [comment]
I test in Windows10, but failed
python :3.6.4
tensorflow :1.14.0
keras:2.2.4
I can't install keras=2.2.5

**Comment by QFaceblue** [comment]
I have successfully run by reinstalling the environment many times
python :3.6.4
tensorflow :1.14.0
keras:2.2.4

**Comment by vihari1729** [comment]
@QFaceblue  Did you able to convert your custom model to keras model?

**Comment by Ivan-basis** [comment]
@vihari1729 I was, using the versions mentioned by @QFaceblue
