### ISSUE TITLE
数据增强方面好像没有使用到mosaic方法

### ISSUE THREAD

**Issue by ZaoYum-Liao** [Ma-Dan/keras-yolo4#19]
大致看了一下，貌似get_random_data()方法里面并没有实现mosaic的数据增强方法？其他的大部分和keras yolov3的差不多~

**Comment by MyNameIsLzy** [comment]
Mosaic数据增强、Label Smoothing平滑、学习率余弦退火衰减似乎这些我都没有见到呢，当然我只是大致看了一下....但我在train.py里面训练函数确实没见到使用...
