### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by saanuregh** [Ma-Dan/keras-yolo4#2]
Loading weights.
Weights Header:  1329865020 1348031555 1952981061 [1010723949]
Converting  0
Traceback (most recent call last):
  File "convert.py", line 173, in <module>
    yolo4_model = Yolo4(score, iou, anchors_path, classes_path, model_path, weights_path)
  File "convert.py", line 157, in __init__
    self.load_yolo()
  File "convert.py", line 130, in load_yolo
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array

**Comment by saanuregh** [comment]
file didnt download properly fixed

**Comment by vihari1729** [comment]
@saanuregh  Did you able to solve the error?. If yes, Kindly provide the solution
I am also getting the same error when converting yolo-custom weights to keras model

**Comment by saanuregh** [comment]
@vihari1729 it was just a download error
